# deploy/docker-compose.yml
version: '3.8'
services:
  lograg:
    build: .
    ports:
      - "8001:8001"
      - "8501:8501"
    volumes:
      - .:/app
    command: >
      sh -c "python api/main.py & 
             streamlit run app.py --server.port=8501 --server.headless=true"